In [1]:
print("NumPy for Beginners in 15 minutes | Python Crash Course")

NumPy for Beginners in 15 minutes | Python Crash Course


In [5]:
print("You\'ll learn How to:-")
print("1. Install NumPy.")
print("2. Create and Transform NumPy Arrays.")
print("3. Apply Mathematical Functions and Export Data.")

You'll learn How to:-
1. Install NumPy.
2. Create and Transform NumPy Arrays.
3. Apply Mathematical Functions and Export Data.


In [6]:
print("Install NumPy")
print("NumPy Arrays")
print("Mathematical Functions")

Install NumPy
NumPy Arrays
Mathematical Functions


In [7]:
print("What is NumPy?")

What is NumPy?


In [8]:
print("""1.Fast,Powerful and Easy 
to use Library for working with Arrays Big and Small.
2.Has support for N-dimensional Arrays.
e.g [1,2,3],[4,5,6],[7,8,9]
3.Useful for working with a large majority of 
Data Science tools Like Pandas and Tensorflow.
""")

1.Fast,Powerful and Easy 
to use Library for working with Arrays Big and Small.
2.Has support for N-dimensional Arrays.
e.g [1,2,3],[4,5,6],[7,8,9]
3.Useful for working with a large majority of 
Data Science tools Like Pandas and Tensorflow.



In [11]:
print("""What's Covered:-
1.Installing NumPy.
2.Working with np for Data Science.
3.Exporting your work.
'Creating Reading Updating and Deleting NumPy Arrarys'
1.Create.
2.Read.
3.Update.
4.Delete.
""")

What's Covered:-
1.Installing NumPy.
2.Working with np for Data Science.
3.Exporting your work.
'Creating Reading Updating and Deleting NumPy Arrarys'
1.Create.
2.Read.
3.Update.
4.Delete.



In [12]:
!pip install numpy

In [13]:
import numpy as np

In [14]:
print("1.Create")

1.Create


In [19]:
#Two[],row=3,column=4.
data = np.random.rand(2,3,4)

In [20]:
print(data)

[[[0.88790606 0.61657275 0.34735263 0.45698572]
  [0.68837249 0.5253554  0.06319619 0.10653006]
  [0.5994093  0.50613144 0.00959431 0.27752234]]

 [[0.34455767 0.12478674 0.99849042 0.78660386]
  [0.00698601 0.34607136 0.3597709  0.36846349]
  [0.10530606 0.72875514 0.85989017 0.94403603]]]


In [21]:
zeroes = np.zeros((2,2,2))

In [22]:
print(zeroes)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [23]:
full = np.full((2,2,2),7)

In [24]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [48]:
ones = np.ones((2,2,2))

In [26]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
data

array([[[0.88790606, 0.61657275, 0.34735263, 0.45698572],
        [0.68837249, 0.5253554 , 0.06319619, 0.10653006],
        [0.5994093 , 0.50613144, 0.00959431, 0.27752234]],

       [[0.34455767, 0.12478674, 0.99849042, 0.78660386],
        [0.00698601, 0.34607136, 0.3597709 , 0.36846349],
        [0.10530606, 0.72875514, 0.85989017, 0.94403603]]])

In [28]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [29]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [30]:
type(arr)

numpy.ndarray

In [56]:
arr2 = np.array([[1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4]])

In [57]:
arr2*2

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [58]:
print("2.Read")

2.Read


In [59]:
shape = data.shape

In [60]:
shape

(2, 3, 4)

In [61]:
size = data.size

In [62]:
types = data.dtype

In [65]:
size#4Columns x 6Rows

24

In [64]:
types

dtype('float64')

In [66]:
#Attributes.
shape = data.shape
size = data.size
types = data.dtype

In [69]:
print(shape)
print(size)
print(types)

(2, 3, 4)
24
float64


In [70]:
print("#Slicing")

#Slicing


In [76]:
arr0 = data[0]
print(arr0)
print("---------")
slicer = data[0:2]
print(slicer)
print("---------")
reverse = data[-1]
print(reverse)
print("---------")
singlevel = data[0][0][0]
print(singlevel)

[[0.88790606 0.61657275 0.34735263 0.45698572]
 [0.68837249 0.5253554  0.06319619 0.10653006]
 [0.5994093  0.50613144 0.00959431 0.27752234]]
---------
[[[0.88790606 0.61657275 0.34735263 0.45698572]
  [0.68837249 0.5253554  0.06319619 0.10653006]
  [0.5994093  0.50613144 0.00959431 0.27752234]]

 [[0.34455767 0.12478674 0.99849042 0.78660386]
  [0.00698601 0.34607136 0.3597709  0.36846349]
  [0.10530606 0.72875514 0.85989017 0.94403603]]]
---------
[[0.34455767 0.12478674 0.99849042 0.78660386]
 [0.00698601 0.34607136 0.3597709  0.36846349]
 [0.10530606 0.72875514 0.85989017 0.94403603]]
---------
0.887906055273492


In [77]:
data

array([[[0.88790606, 0.61657275, 0.34735263, 0.45698572],
        [0.68837249, 0.5253554 , 0.06319619, 0.10653006],
        [0.5994093 , 0.50613144, 0.00959431, 0.27752234]],

       [[0.34455767, 0.12478674, 0.99849042, 0.78660386],
        [0.00698601, 0.34607136, 0.3597709 , 0.36846349],
        [0.10530606, 0.72875514, 0.85989017, 0.94403603]]])

In [78]:
print("3.Update")

3.Update


In [90]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)
list1

array([0.92169946, 0.82242872, 0.95133747, 0.83822974, 0.90130472,
       0.54978931, 0.83971847, 0.99830812, 0.05106181, 0.19325047])

In [80]:
list2

array([0.18732246, 0.50048185, 0.86351358, 0.62095568, 0.13051768,
       0.98201768, 0.83133066, 0.58621411, 0.74505364, 0.06631114])

In [81]:
print("# Basic Math")

# Basic Math


In [83]:
#add,subtract,divide,multiply and dot Array By Array.
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mult = np.multiply(list1,list2)
dot = np.dot(list1,list2)

In [84]:
add

array([0.48730275, 1.05618648, 1.78549633, 0.73320223, 0.29348141,
       1.80870766, 1.2372414 , 1.27691817, 1.65209726, 0.48816782])

In [85]:
sub

array([ 0.11265783,  0.05522277,  0.05846917, -0.50870912,  0.03244605,
       -0.1553277 , -0.42541992,  0.10448995,  0.16198998,  0.35554555])

In [86]:
div

array([1.60141122, 1.1103392 , 1.06771077, 0.1807642 , 1.24859503,
       0.841828  , 0.48826629, 1.17824537, 1.21742055, 6.36177738])

In [87]:
mult

array([0.05619305, 0.27812008, 0.79614463, 0.06970013, 0.02126965,
       0.81182418, 0.33744605, 0.40490047, 0.67579615, 0.0279738 ])

In [88]:
dot

3.4793681716823137

In [93]:
# Calculated Functions.

In [101]:
sqrt = np.sqrt(25)#Root 25.
print(sqrt)
ab = np.abs(-2)
print(ab)
power = np.power(2,7)
print(power)
log = np.log(25)
print(log)
exp = ([2,3])
print(exp)

5.0
2
128
3.2188758248682006
[2, 3]


In [102]:
mins = np.min([list1])
maxs = np.max(list1)

In [103]:
mins

0.05106180559364848

In [104]:
maxs

0.9983081228637499

In [105]:
exp = np.exp([2,3])

In [107]:
exp

array([ 7.3890561 , 20.08553692])

In [110]:
data

array([[[0.88790606, 0.61657275, 0.34735263, 0.45698572],
        [0.68837249, 0.5253554 , 0.06319619, 0.10653006],
        [0.5994093 , 0.50613144, 0.00959431, 0.27752234]],

       [[0.34455767, 0.12478674, 0.99849042, 0.78660386],
        [0.00698601, 0.34607136, 0.3597709 , 0.36846349],
        [0.10530606, 0.72875514, 0.85989017, 0.94403603]]])

In [111]:
#First Element in the Array.
data[0][0][0]

0.887906055273492

In [114]:
data[0][0][0] = 700#Update-Data.

In [115]:
data

array([[[7.00000000e+02, 6.16572754e-01, 3.47352631e-01, 4.56985724e-01],
        [6.88372490e-01, 5.25355400e-01, 6.31961943e-02, 1.06530065e-01],
        [5.99409301e-01, 5.06131443e-01, 9.59431481e-03, 2.77522342e-01]],

       [[3.44557668e-01, 1.24786737e-01, 9.98490423e-01, 7.86603860e-01],
        [6.98601115e-03, 3.46071363e-01, 3.59770904e-01, 3.68463494e-01],
        [1.05306063e-01, 7.28755140e-01, 8.59890172e-01, 9.44036029e-01]]])

In [116]:
data.sort()

In [117]:
data

array([[[3.47352631e-01, 4.56985724e-01, 6.16572754e-01, 7.00000000e+02],
        [6.31961943e-02, 1.06530065e-01, 5.25355400e-01, 6.88372490e-01],
        [9.59431481e-03, 2.77522342e-01, 5.06131443e-01, 5.99409301e-01]],

       [[1.24786737e-01, 3.44557668e-01, 7.86603860e-01, 9.98490423e-01],
        [6.98601115e-03, 3.46071363e-01, 3.59770904e-01, 3.68463494e-01],
        [1.05306063e-01, 7.28755140e-01, 8.59890172e-01, 9.44036029e-01]]])

In [118]:
print('4.Delete')

4.Delete


In [119]:
print(data.shape)

(2, 3, 4)


In [125]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [128]:
zeros = np.zeros(8)
print(zeros)
zeros = np.append(zeros,[3,4])
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [131]:
#Insert 1 in position 2.
zeros= np.insert(zeros,2,1)
print(zeros)

[0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [132]:
print("4.Delete")

4.Delete


In [133]:
data

array([[[3.47352631e-01, 4.56985724e-01, 6.16572754e-01, 7.00000000e+02,
         6.31961943e-02, 1.06530065e-01],
        [5.25355400e-01, 6.88372490e-01, 9.59431481e-03, 2.77522342e-01,
         5.06131443e-01, 5.99409301e-01]],

       [[1.24786737e-01, 3.44557668e-01, 7.86603860e-01, 9.98490423e-01,
         6.98601115e-03, 3.46071363e-01],
        [3.59770904e-01, 3.68463494e-01, 1.05306063e-01, 7.28755140e-01,
         8.59890172e-01, 9.44036029e-01]]])

In [135]:
#Delete The Axis 1 From data.
np.delete(data,0,axis=1)

array([[[0.5253554 , 0.68837249, 0.00959431, 0.27752234, 0.50613144,
         0.5994093 ]],

       [[0.3597709 , 0.36846349, 0.10530606, 0.72875514, 0.85989017,
         0.94403603]]])

In [136]:
np.save("new array",data)

In [137]:
test = np.load("new array.npy")

In [138]:
test

array([[[3.47352631e-01, 4.56985724e-01, 6.16572754e-01, 7.00000000e+02,
         6.31961943e-02, 1.06530065e-01],
        [5.25355400e-01, 6.88372490e-01, 9.59431481e-03, 2.77522342e-01,
         5.06131443e-01, 5.99409301e-01]],

       [[1.24786737e-01, 3.44557668e-01, 7.86603860e-01, 9.98490423e-01,
         6.98601115e-03, 3.46071363e-01],
        [3.59770904e-01, 3.68463494e-01, 1.05306063e-01, 7.28755140e-01,
         8.59890172e-01, 9.44036029e-01]]])

In [139]:
print("NumPy for Beginners in 15 minutes | Python Crash Course Finished")

NumPy for Beginners in 15 minutes | Python Crash Course Finished


In [140]:
print(
"""
>>NumPy>>(Numerical Python) Arrays.
Mathematical Functions.
Linear Algebra.
"""
)


>>NumPy>>(Numerical Python) Arrays.
Mathematical Functions.
Linear Algebra.



In [141]:
print("""Ask ChatGPT>>NumPy most used Modules.
>>NumPy has several Modules and Submodules that are frequently 
used in various Scientific Computing and Data Analysis Tasks. 
Here are some of the most commonly used modules in NumPy.
""")

Ask ChatGPT>>NumPy most used Modules.
>>NumPy has several Modules and Submodules that are frequently 
used in various Scientific Computing and Data Analysis Tasks. 
Here are some of the most commonly used modules in NumPy.



In [142]:
print("NumPy:-The fundamental package for scientific computing with Python")

NumPy:-The fundamental package for scientific computing with Python


In [143]:
print("Complete>>NumPy Documentation And Ask ChatGPT")

Complete>>NumPy Documentation And Ask ChatGPT
